Alias: $SCT = http://snomed.info/sct
Alias: $UCUM = http://unitsofmeasure.org
Alias: $LOINC = http://loinc.org
Alias: $ISCO08 = https://profiles.ihe.net/PCC/ODH/CodeSystem/ISCO08
Alias: $ISICRev4 = https://profiles.ihe.net/PCC/ODH/CodeSystem/ISICRev4
Alias: $ICD10 = http://hl7.org/fhir/sid/icd-10
Alias: $ICD10-CM = http://hl7.org/fhir/sid/icd-10-cm
Alias: $m49.htm = http://unstats.un.org/unsd/methods/m49/m49.htm
Alias: $StructureDefinition-Patient-uv-ips.html = https://hl7.org/fhir/uv/ips/StructureDefinition-Patient-uv-ips.html
Alias: $referencerange-meaning = http://hl7.org/fhir/ValueSet/referencerange-meaning
Alias: $2.16.840.1.113883.12.292 = https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.12.292
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category
